In [ ]:
import pandas as pd
import numpy as np

file='pokemon.csv'
df=pd.read_csv(file)
df

# NaN -> missing values
#numerical->regression   categorical->classification

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [ ]:
df.head(10)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,6,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,7,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,8,Mega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,9,Mega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
9,10,Squirtle,Water,NaN,44,48,65,50,64,43,1,False

In [ ]:
df.tail()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
df.shape # gives rows and columns

(800, 12)

In [ ]:
df.info()   # name->799 values nd 1 is missing out of 800 rows #->has all serial nos i.e 800 Type1->has all the 800 values so on....

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        799 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

In [ ]:
df.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

In [ ]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [ ]:
df.isnull()   #false->not missing true->missing

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,False,False,False,False,False,False,False,False,False,False,False,False
796,False,False,False,False,False,False,False,False,False,False,False,False
797,False,False,False,False,False,False,False,False,False,False,False,False
798,False,False,False,False,False,False,False,False,False,False,False,False
799,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()  #name-> has 1 missing value type2->386 missing values it will sum all the trues which have missiong values in isnull()

#               0
Name            1
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
df.nunique() #It will return the count of unique values and it will help you to decide which features are numerical and categorical i.e type1,type2,generation,legendary can become categorical becoz of small values.If too large values are there like 800,95,799 then it's numerical

#             800
Name          799
Type 1         18
Type 2         18
HP             94
Attack        111
Defense       103
Sp. Atk       105
Sp. Def        92
Speed         108
Generation      6
Legendary       2
dtype: int64

In [ ]:
df['Name'].unique()

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'Mega Venusaur', 'Charmander',
       'Charmeleon', 'Charizard', 'Mega Charizard X', 'Mega Charizard Y',
       'Squirtle', 'Wartortle', 'Blastoise', 'Mega Blastoise', 'Caterpie',
       'Metapod', 'Butterfree', 'Weedle', 'Kakuna', 'Beedrill',
       'Mega Beedrill', 'Pidgey', 'Pidgeotto', 'Pidgeot', 'Mega Pidgeot',
       'Rattata', 'Raticate', 'Spearow', 'Fearow', 'Ekans', 'Arbok',
       'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash', 'Nidoranâ™€',
       'Nidorina', 'Nidoqueen', 'Nidoranâ™‚', 'Nidorino', 'Nidoking',
       'Clefairy', 'Clefable', 'Vulpix', 'Ninetales', 'Jigglypuff',
       'Wigglytuff', 'Zubat', 'Golbat', 'Oddish', 'Gloom', 'Vileplume',
       'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Diglett', 'Dugtrio',
       'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey', nan,
       'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl', 'Poliwrath',
       'Abra', 'Kadabra', 'Alakazam', 'Mega Alakazam', 'Machop',
       'Machoke', 'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel',
       'Tentacool', 'Tentacruel', 'Geodude', 'Graveler', 'Golem',
       'Ponyta', 'Rapidash', 'Slowpoke', 'Slowbro', 'Mega Slowbro',
       'Magnemite', 'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel',
       'Dewgong', 'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly',
       'Haunter', 'Gengar', 'Mega Gengar', 'Onix', 'Drowzee', 'Hypno',
       'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'Mega Kangaskhan', 'Horsea', 'Seadra',
       'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime', 'Scyther',
       'Jynx', 'Electabuzz', 'Magmar', 'Pinsir', 'Mega Pinsir', 'Tauros',
       'Magikarp', 'Gyarados', 'Mega Gyarados', 'Lapras', 'Ditto',
       'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Omanyte',
       'Omastar', 'Kabuto', 'Kabutops', 'Aerodactyl', 'Mega Aerodactyl',
       'Snorlax', 'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'Mega Mewtwo X', 'Mega Mewtwo Y', 'Mew',
       'Chikorita', 'Bayleef', 'Meganium', 'Cyndaquil', 'Quilava',
       'Typhlosion', 'Totodile', 'Croconaw', 'Feraligatr', 'Sentret',
       'Furret', 'Hoothoot', 'Noctowl', 'Ledyba', 'Ledian', 'Spinarak',
       'Ariados', 'Crobat', 'Chinchou', 'Lanturn', 'Pichu', 'Cleffa',
       'Igglybuff', 'Togepi', 'Togetic', 'Natu', 'Xatu', 'Mareep',
       'Flaaffy', 'Ampharos', 'Mega Ampharos', 'Bellossom', 'Marill',
       'Azumarill', 'Sudowoodo', 'Politoed', 'Hoppip', 'Skiploom',
       'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora', 'Yanma', 'Wooper',
       'Quagsire', 'Espeon', 'Umbreon', 'Murkrow', 'Slowking',
       'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig', 'Pineco',
       'Forretress', 'Dunsparce', 'Gligar', 'Steelix', 'Mega Steelix',
       'Snubbull', 'Granbull', 'Qwilfish', 'Scizor', 'Mega Scizor',
       'Shuckle', 'Heracross', 'Mega Heracross', 'Sneasel', 'Teddiursa',
       'Ursaring', 'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola',
       'Remoraid', 'Octillery', 'Delibird', 'Mantine', 'Skarmory',
       'Houndour', 'Houndoom', 'Mega Houndoom', 'Kingdra', 'Phanpy',
       'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue',
       'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey',
       'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar',
       'Mega Tyranitar', 'Lugia', 'Ho-oh', 'Celebi', 'Treecko', 'Grovyle',
       'Sceptile', 'Mega Sceptile', 'Torchic', 'Combusken', 'Blaziken',
       'Mega Blaziken', 'Mudkip', 'Marshtomp', 'Swampert',
       'Mega Swampert', 'Poochyena', 'Mightyena', 'Zigzagoon', 'Linoone',
       'Wurmple', 'Silcoon', 'Beautifly', 'Cascoon', 'Dustox', 'Lotad',
       'Lombre', 'Ludicolo', 'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow',
       'Swellow', 'Wingull', 'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
       'Mega Gardevoir', 'Surskit', 'Masquerain', 'Shroomish', 'Breloom',
       'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask', 'Shedinja',
       'Whismur', 'Loudred', 'Exploud', 'Makuhita', 'Hariyama', 'Azurill',
       'Nosepass', 'Skitty', 'Delcatty', 'Sableye', 'Mega Sableye',
       'Mawile', 'Mega Mawile', 'Aron', 'Lairon', 'Aggron', 'Mega Aggron',
       'Meditite', 'Medicham', 'Mega Medicham', 'Electrike', 'Manectric',
       'Mega Manectric', 'Plusle', 'Minun', 'Volbeat', 'Illumise',
       'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo',
       'Mega Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
       'Mega Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'Mega Altaria', 'Zangoose', 'Seviper', 'Lunatone',
       'Solrock', 'Barboach', 'Whiscash', 'Corphish', 'Crawdaunt',
       'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith', 'Armaldo',
       'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet', 'Banette',
       'Mega Banette', 'Duskull', 'Dusclops', 'Tropius', 'Chimecho',
       'Absol', 'Mega Absol', 'Wynaut', 'Snorunt', 'Glalie',
       'Mega Glalie', 'Spheal', 'Sealeo', 'Walrein', 'Clamperl',
       'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon', 'Shelgon',
       'Salamence', 'Mega Salamence', 'Beldum', 'Metang', 'Metagross',
       'Mega Metagross', 'Regirock', 'Regice', 'Registeel', 'Latias',
       'Mega Latias', 'Latios', 'Mega Latios', 'Kyogre', 'Primal Kyogre',
       'Groudon', 'Primal Groudon', 'Rayquaza', 'Mega Rayquaza',
       'Jirachi', 'Deoxys Normal Forme', 'DeoxysAttack Forme',
       'Deoxys Defense Forme', 'Deoxys Speed Forme', 'Turtwig', 'Grotle',
       'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup',
       'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor',
       'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio',
       'Luxray', 'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon',
       'Bastiodon', 'Burmy', 'Wormadam Plant Cloak',
       'Wormadam Sandy Cloak', 'Wormadam Trash Cloak', 'Mothim', 'Combee',
       'Vespiquen', 'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi',
       'Cherrim', 'Shellos', 'Gastrodon', 'Ambipom', 'Drifloon',
       'Drifblim', 'Buneary', 'Lopunny', 'Mega Lopunny', 'Mismagius',
       'Honchkrow', 'Glameow', 'Purugly', 'Chingling', 'Stunky',
       'Skuntank', 'Bronzor', 'Bronzong', 'Bonsly', 'Mime Jr.', 'Happiny',
       'Chatot', 'Spiritomb', 'Gible', 'Gabite', 'Garchomp',
       'Mega Garchomp', 'Munchlax', 'Riolu', 'Lucario', 'Mega Lucario',
       'Hippopotas', 'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk',
       'Toxicroak', 'Carnivine', 'Finneon', 'Lumineon', 'Mantyke',
       'Snover', 'Abomasnow', 'Mega Abomasnow', 'Weavile', 'Magnezone',
       'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
       'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor',
       'Mamoswine', 'Porygon-Z', 'Gallade', 'Mega Gallade', 'Probopass',
       'Dusknoir', 'Froslass', 'Rotom', 'Heat Rotom', 'Wash Rotom',
       'Frost Rotom', 'Fan Rotom', 'Mow Rotom', 'Uxie', 'Mesprit',
       'Azelf', 'Dialga', 'Palkia', 'Heatran', 'Regigigas',
       'Giratina Altered Forme', 'Giratina Origin Forme', 'Cresselia',
       'Phione', 'Manaphy', 'Darkrai', 'Shaymin Land Forme',
       'Shaymin Sky Forme', 'Arceus', 'Victini', 'Snivy', 'Servine',
       'Serperior', 'Tepig', 'Pignite', 'Emboar', 'Oshawott', 'Dewott',
       'Samurott', 'Patrat', 'Watchog', 'Lillipup', 'Herdier',
       'Stoutland', 'Purrloin', 'Liepard', 'Pansage', 'Simisage',
       'Pansear', 'Simisear', 'Panpour', 'Simipour', 'Munna', 'Musharna',
       'Pidove', 'Tranquill', 'Unfezant', 'Blitzle', 'Zebstrika',
       'Roggenrola', 'Boldore', 'Gigalith', 'Woobat', 'Swoobat',
       'Drilbur', 'Excadrill', 'Audino', 'Mega Audino', 'Timburr',
       'Gurdurr', 'Conkeldurr', 'Tympole', 'Palpitoad', 'Seismitoad',
       'Throh', 'Sawk', 'Sewaddle', 'Swadloon', 'Leavanny', 'Venipede',
       'Whirlipede', 'Scolipede', 'Cottonee', 'Whimsicott', 'Petilil',
       'Lilligant', 'Basculin', 'Sandile', 'Krokorok', 'Krookodile',
       'Darumaka', 'Darmanitan Standard Mode', 'Darmanitan Zen Mode',
       'Maractus', 'Dwebble', 'Crustle', 'Scraggy', 'Scrafty', 'Sigilyph',
       'Yamask', 'Cofagrigus', 'Tirtouga', 'Carracosta', 'Archen',
       'Archeops', 'Trubbish', 'Garbodor', 'Zorua', 'Zoroark', 'Minccino',
       'Cinccino', 'Gothita', 'Gothorita', 'Gothitelle', 'Solosis',
       'Duosion', 'Reuniclus', 'Ducklett', 'Swanna', 'Vanillite',
       'Vanillish', 'Vanilluxe', 'Deerling', 'Sawsbuck', 'Emolga',
       'Karrablast', 'Escavalier', 'Foongus', 'Amoonguss', 'Frillish',
       'Jellicent', 'Alomomola', 'Joltik', 'Galvantula', 'Ferroseed',
       'Ferrothorn', 'Klink', 'Klang', 'Klinklang', 'Tynamo', 'Eelektrik',
       'Eelektross', 'Elgyem', 'Beheeyem', 'Litwick', 'Lampent',
       'Chandelure', 'Axew', 'Fraxure', 'Haxorus', 'Cubchoo', 'Beartic',
       'Cryogonal', 'Shelmet', 'Accelgor', 'Stunfisk', 'Mienfoo',
       'Mienshao', 'Druddigon', 'Golett', 'Golurk', 'Pawniard', 'Bisharp',
       'Bouffalant', 'Rufflet', 'Braviary', 'Vullaby', 'Mandibuzz',
       'Heatmor', 'Durant', 'Deino', 'Zweilous', 'Hydreigon', 'Larvesta',
       'Volcarona', 'Cobalion', 'Terrakion', 'Virizion',
       'Tornadus Incarnate Forme', 'Tornadus Therian Forme',
       'Thundurus Incarnate Forme', 'Thundurus Therian Forme', 'Reshiram',
       'Zekrom', 'Landorus Incarnate Forme', 'Landorus Therian Forme',
       'Kyurem', 'Kyurem Black Kyurem', 'Kyurem White Kyurem',
       'Keldeo Ordinary Forme', 'Keldeo Resolute Forme',
       'Meloetta Aria Forme', 'Meloetta Pirouette Forme', 'Genesect',
       'Chespin', 'Quilladin', 'Chesnaught', 'Fennekin', 'Braixen',
       'Delphox', 'Froakie', 'Frogadier', 'Greninja', 'Bunnelby',
       'Diggersby', 'Fletchling', 'Fletchinder', 'Talonflame',
       'Scatterbug', 'Spewpa', 'Vivillon', 'Litleo', 'Pyroar', 'FlabÃ©bÃ©',
       'Floette', 'Florges', 'Skiddo', 'Gogoat', 'Pancham', 'Pangoro',
       'Furfrou', 'Espurr', 'Meowstic Male', 'Meowstic Female', 'Honedge',
       'Doublade', 'Aegislash Blade Forme', 'Aegislash Shield Forme',
       'Spritzee', 'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay',
       'Malamar', 'Binacle', 'Barbaracle', 'Skrelp', 'Dragalge',
       'Clauncher', 'Clawitzer', 'Helioptile', 'Heliolisk', 'Tyrunt',
       'Tyrantrum', 'Amaura', 'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne',
       'Carbink', 'Goomy', 'Sliggoo', 'Goodra', 'Klefki', 'Phantump',
       'Trevenant', 'Pumpkaboo Average Size', 'Pumpkaboo Small Size',
       'Pumpkaboo Large Size', 'Pumpkaboo Super Size',
       'Gourgeist Average Size', 'Gourgeist Small Size',
       'Gourgeist Large Size', 'Gourgeist Super Size', 'Bergmite',
       'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal',
       'Zygarde Half Forme', 'Diancie', 'Mega Diancie', 'Hoopa Confined',
       'Hoopa Unbound', 'Volcanion'], dtype=object)

In [ ]:
df['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [ ]:
df.describe() #works only on numeric features.for eg Name wont be considered becoz its string likewise

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.0000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,400.5000,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,231.0844,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.0000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,200.7500,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,400.5000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,600.2500,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,800.0000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

# Column Operations

In [ ]:
df['Name'] #1d

0           Bulbasaur
1             Ivysaur
2            Venusaur
3       Mega Venusaur
4          Charmander
            ...
795           Diancie
796      Mega Diancie
797    Hoopa Confined
798     Hoopa Unbound
799         Volcanion
Name: Name, Length: 800, dtype: object

In [ ]:
df[['Name']]  #to make it 2d from 1d

               Name
0         Bulbasaur
1           Ivysaur
2          Venusaur
3     Mega Venusaur
4        Charmander
..              ...
795         Diancie
796    Mega Diancie
797  Hoopa Confined
798   Hoopa Unbound
799       Volcanion

[800 rows x 1 columns]

In [ ]:
df[['Name','Type 1']]  # to see 2 columns together

               Name   Type 1
0         Bulbasaur    Grass
1           Ivysaur    Grass
2          Venusaur    Grass
3     Mega Venusaur    Grass
4        Charmander     Fire
..              ...      ...
795         Diancie     Rock
796    Mega Diancie     Rock
797  Hoopa Confined  Psychic
798   Hoopa Unbound  Psychic
799       Volcanion     Fire

[800 rows x 2 columns]

In [ ]:
#adding new column to dataframe
df['Difference']=df['Attack']-df['Defense']

In [ ]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Difference
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,0
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,-1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,-1
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,-23
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,9

In [ ]:
#Removing any column

df.drop(['Difference'],axis=1)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
df #After removing difference column if we try to print df again difference column is still there

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Difference
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,0
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,-1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,-1
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,-23
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,-50
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,50
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,50
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,100
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,-10

In [ ]:
df.drop(['Difference'],inplace=True,axis=1)  #to rectify above error and make changes visible we will use inplace

In [ ]:
df  # now difference column won't appear

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

# Row Operations

In [ ]:
df.iloc[0]   #it will give all the information at 0th row

#                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object

In [ ]:
#slicing
df.iloc[4:20,:5]  # rows-> start 4 till 19th row  columns-> start 0->4th column

     #              Name Type 1  Type 2  HP
4    5        Charmander   Fire     NaN  39
5    6        Charmeleon   Fire     NaN  58
6    7         Charizard   Fire  Flying  78
7    8  Mega Charizard X   Fire  Dragon  78
8    9  Mega Charizard Y   Fire  Flying  78
9   10          Squirtle  Water     NaN  44
10  11         Wartortle  Water     NaN  59
11  12         Blastoise  Water     NaN  79
12  13    Mega Blastoise  Water     NaN  79
13  14          Caterpie    Bug     NaN  45
14  15           Metapod    Bug     NaN  50
15  16        Butterfree    Bug  Flying  60
16  17            Weedle    Bug  Poison  40
17  18            Kakuna    Bug  Poison  45
18  19          Beedrill    Bug  Poison  65
19  20     Mega Beedrill    Bug  Poison  65

In [ ]:
# remove particular rows
df.drop(index=2,inplace=True,axis=0)

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,6,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
#to remove particular column
df.drop(['#'],inplace=True,axis=1)

In [ ]:
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

# Rename

In [ ]:
df.rename(columns={'HP':'Health Points'},inplace=True)

In [ ]:
df.head()

,Name,Type 1,Type 2,Health Points,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False

# Set_Index()

In [ ]:
df=df.set_index('Name')  #to make our own indexing instead of default raw indexing (i.e 0,1,2....) now Name is not a row it has become index

In [ ]:
df.head()

,Type 1,Type 2,Health Points,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,
Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
Charmander,Fire,NaN,39,52,43,60,50,65,1,False
Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False

In [ ]:
df.loc['Ivysaur']   # now that we have created our own indexing we will use loc to access the records instead of iloc

Type 1            Grass
Type 2           Poison
Health Points        60
Attack               62
Defense              63
Sp. Atk              80
Sp. Def              80
Speed                60
Generation            1
Legendary         False
Name: Ivysaur, dtype: object

# Reset Index

In [ ]:
df.reset_index()  # to reset the index i.e Name back to default index

,Name,Type 1,Type 2,Health Points,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
3,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
4,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...
794,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
795,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
796,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
797,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
798,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

# Q. How many type 1 pokemons are there

In [ ]:
type_1=df['Type 1'].nunique()
print("No Of Type 1 pokemons:",type_1)

No Of Type 1 pokemons: 18

# Q. How many type 2 pokemons are there

In [ ]:
type_2=df['Type 2'].nunique()
print("No Of Type 2 pokemons:",type_2)

No Of Type 2 pokemons: 18

# Q. What are the different variants of Type 1

In [ ]:
type_1_names=df['Type 1'].unique()
print("Different Variants Of Type 1 pokemons:",type_1_names)

Different Variants Of Type 1 pokemons: ['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Poison' 'Electric' 'Ground'
 'Fairy' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Ice' 'Dragon' 'Dark' 'Steel'
 'Flying']

# Values count

In [ ]:
# To show how many times a particular value is repeated.for eg->water is repeated 112 times
type_1_count=df['Type 1'].value_counts()
type_1_count

Water       112
Normal       98
Grass        69
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

In [ ]:
df['Defense'].max()

230

In [ ]:
df['Defense'].idxmax()   #it will give the row number of maximum value. here 230 max value of defence will be at 224th row

224

In [ ]:
df['Defense'].min()

5

In [ ]:
df['Defense'].idxmin()

121